"""
threat_engine/ticket_export.py
Push individual threats to GitHub Issues or Jira as trackable tickets.
Requires env vars:
  GITHUB_TOKEN + GITHUB_REPO  (owner/repo)   — for GitHub
  JIRA_BASE_URL + JIRA_EMAIL + JIRA_API_TOKEN + JIRA_PROJECT_KEY — for Jira
"""
from __future__ import annotations
import os, json, re
import urllib.request, urllib.error

SEV_TO_GITHUB_LABEL = {
    "Critical": "priority: critical",
    "High":     "priority: high",
    "Medium":   "priority: medium",
    "Low":      "priority: low",
    "Info":     "priority: info",
}
SEV_TO_JIRA_PRIORITY = {
    "Critical": "Highest",
    "High":     "High",
    "Medium":   "Medium",
    "Low":      "Low",
    "Info":     "Lowest",
}


def _http(method: str, url: str, headers: dict, body: dict | None = None) -> dict:
    data = json.dumps(body).encode() if body else None
    req  = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        raise RuntimeError(f"HTTP {e.code}: {e.read().decode()}") from e


def create_github_issue(threat: dict, system_name: str) -> dict:
    """Create a GitHub Issue for a threat. Returns {url, number}."""
    token = os.getenv("GITHUB_TOKEN")
    repo  = os.getenv("GITHUB_REPO")
    if not token or not repo:
        raise RuntimeError("Set GITHUB_TOKEN and GITHUB_REPO env vars")

    sev   = threat.get("severity", "Medium")
    title = f"[{sev}] {threat.get('title', 'Threat')} — {system_name}"
    body  = _issue_body_md(threat, system_name)
    label = SEV_TO_GITHUB_LABEL.get(sev, "security")

    result = _http(
        "POST",
        f"https://api.github.com/repos/{repo}/issues",
        {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json",
        },
        {"title": title, "body": body, "labels": ["security", label]},
    )
    return {"url": result["html_url"], "number": result["number"], "provider": "github"}


def create_jira_issue(threat: dict, system_name: str) -> dict:
    """Create a Jira issue for a threat. Returns {url, key}."""
    base     = os.getenv("JIRA_BASE_URL", "").rstrip("/")
    email    = os.getenv("JIRA_EMAIL")
    token    = os.getenv("JIRA_API_TOKEN")
    proj_key = os.getenv("JIRA_PROJECT_KEY")
    if not all([base, email, token, proj_key]):
        raise RuntimeError("Set JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN, JIRA_PROJECT_KEY env vars")

    import base64 as _b64
    creds = _b64.b64encode(f"{email}:{token}".encode()).decode()
    sev   = threat.get("severity", "Medium")

    result = _http(
        "POST",
        f"{base}/rest/api/3/issue",
        {
            "Authorization": f"Basic {creds}",
            "Content-Type":  "application/json",
            "Accept":        "application/json",
        },
        {
            "fields": {
                "project":     {"key": proj_key},
                "summary":     f"[ATM][{sev}] {threat.get('title', 'Threat')}",
                "description": {
                    "type": "doc", "version": 1,
                    "content": [{"type": "paragraph", "content": [
                        {"type": "text", "text": _issue_body_plain(threat, system_name)}
                    ]}]
                },
                "issuetype": {"name": "Bug"},
                "priority":  {"name": SEV_TO_JIRA_PRIORITY.get(sev, "Medium")},
                "labels":    ["security", "threat-model"],
            }
        },
    )
    key = result.get("key", "")
    return {"url": f"{base}/browse/{key}", "key": key, "provider": "jira"}


def _issue_body_md(threat: dict, system_name: str) -> str:
    cvss  = threat.get("cvss31", {})
    dread = threat.get("dread", {})
    mits  = threat.get("mitigations", [])
    return f"""## Threat Model Finding — {system_name}

**Severity:** {threat.get("severity", "Unknown")}
**Methodology:** {threat.get("methodology", "").upper()}
**Category:** {threat.get("category", "")}
**Component:** {threat.get("component_name", "")}
{"**Cross-boundary:** Yes ⚠️" if threat.get("cross_boundary") else ""}
{"**CVSS 3.1:** " + str(cvss.get("score", "")) + " (" + cvss.get("vector", "") + ")" if cvss else ""}
{"**DREAD Score:** " + str(dread.get("total", "")) + "/50" if dread else ""}

### Description
{threat.get("description", "")}

### Mitigations
{"".join(f"- {m}" + chr(10) for m in (mits if isinstance(mits, list) else [mits]))}

---
*Generated by [Automated Threat Modeler](https://github.com/rootabhi1/Automated-Threat-Modelling)*
"""


def _issue_body_plain(threat: dict, system_name: str) -> str:
    mits = threat.get("mitigations", [])
    if isinstance(mits, list):
        mits_str = "; ".join(mits)
    else:
        mits_str = str(mits)
    return (
        f"System: {system_name} | Severity: {threat.get('severity')} | "
        f"Component: {threat.get('component_name')} | "
        f"Description: {threat.get('description', '')} | "
        f"Mitigations: {mits_str}"
    )
